import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:dio/dio.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;
import 'package:firebase_storage/firebase_storage.dart';
import 'package:get_it/get_it.dart';
import 'package:icare/src/features/tiny_tales/domain/usecases/is_tiny_tale_bookmarked_by_me.dart';
import 'package:image_picker/image_picker.dart';
import 'package:internet_connection_checker/internet_connection_checker.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'package:icare/src/config/router/app_router.dart';
import 'package:icare/src/core/api/api_service.dart';
import 'package:icare/src/core/api/dio_factory.dart';
import 'package:icare/src/core/helpers/cache_helper.dart';
import 'package:icare/src/core/network/network_info.dart';
import 'package:icare/src/features/auth/data/datasources/forgot_password_datasource.dart';
import 'package:icare/src/features/auth/data/datasources/login_datasource.dart';
import 'package:icare/src/features/auth/data/datasources/register_datasource.dart';
import 'package:icare/src/features/auth/data/repositories/forgot_password_repo.dart';
import 'package:icare/src/features/auth/data/repositories/login_repo.dart';
import 'package:icare/src/features/auth/data/repositories/register_repo_impl.dart';
import 'package:icare/src/features/auth/domain/repositories/register_repo.dart';
import 'package:icare/src/features/auth/domain/usecases/create_firestore_user.dart';
import 'package:icare/src/features/auth/domain/usecases/forgot_password.dart';
import 'package:icare/src/features/auth/domain/usecases/login.dart';
import 'package:icare/src/features/auth/domain/usecases/register.dart';
import 'package:icare/src/features/auth/domain/usecases/sign_in_with_google.dart';
import 'package:icare/src/features/auth/presentation/cubits/forgot_password/forgot_password_cubit.dart';
import 'package:icare/src/features/auth/presentation/cubits/login/login_cubit.dart';
import 'package:icare/src/features/auth/presentation/cubits/register/register_cubit.dart';
import 'package:icare/src/features/baby_cry_predictor/data/datasources/baby_cry_predictor_datasource.dart';
import 'package:icare/src/features/baby_cry_predictor/data/repositories/baby_cry_predictor_repo.dart';
import 'package:icare/src/features/baby_cry_predictor/domain/usecases/baby_cry_predictor.dart';
import 'package:icare/src/features/baby_cry_predictor/presentation/cubit/baby_cry_predictor_cubit.dart';
import 'package:icare/src/features/comments/data/datasources/comment_replies_datasource.dart';
import 'package:icare/src/features/comments/data/datasources/comment_replies_datasource_impl.dart';
import 'package:icare/src/features/comments/data/datasources/comments_remote_datasource.dart';
import 'package:icare/src/features/comments/data/datasources/comments_remote_datasource_impl.dart';
import 'package:icare/src/features/comments/data/repositories/comment_replies_repo_impl.dart';
import 'package:icare/src/features/comments/data/repositories/comments_repo_impl.dart';
import 'package:icare/src/features/comments/domain/repositories/comment_replies_repo.dart';
import 'package:icare/src/features/comments/domain/repositories/comments_repo.dart';
import 'package:icare/src/features/comments/domain/usecases/delete_comment.dart';
import 'package:icare/src/features/comments/domain/usecases/delete_comment_reply.dart';
import 'package:icare/src/features/comments/domain/usecases/get_comment_replies.dart';
import 'package:icare/src/features/comments/domain/usecases/is_comment_liked_by_me.dart';
import 'package:icare/src/features/comments/domain/usecases/is_comment_reply_liked_by_me.dart';
import 'package:icare/src/features/comments/domain/usecases/like_comment.dart';
import 'package:icare/src/features/comments/domain/usecases/like_comment_reply.dart';
import 'package:icare/src/features/comments/domain/usecases/stream_comments.dart';
import 'package:icare/src/features/comments/domain/usecases/type_new_comment.dart';
import 'package:icare/src/features/comments/domain/usecases/type_new_comment_reply.dart';
import 'package:icare/src/features/comments/domain/usecases/unlike_comment.dart';
import 'package:icare/src/features/comments/domain/usecases/unlike_comment_reply.dart';
import 'package:icare/src/features/comments/domain/usecases/upload_comment_image.dart';
import 'package:icare/src/features/comments/domain/usecases/upload_comment_reply_image.dart';
import 'package:icare/src/features/comments/presentation/cubits/comment_replies/comment_replies_cubit.dart';
import 'package:icare/src/features/comments/presentation/cubits/comments/comments_cubit.dart';
import 'package:icare/src/features/disease_details/data/datasources/disease_details_local_datasource.dart';
import 'package:icare/src/features/disease_details/data/datasources/emergency_disease_details_remote_datasource.dart';
import 'package:icare/src/features/disease_details/data/datasources/medical_info_disease_details_remote_datasource.dart';
import 'package:icare/src/features/disease_details/data/repositories/emergency_disease_details_repo.dart';
import 'package:icare/src/features/disease_details/data/repositories/medical_info_disease_details_repo.dart';
import 'package:icare/src/features/disease_details/domain/usecases/get_emergency_disease_details.dart';
import 'package:icare/src/features/disease_details/domain/usecases/get_medical_info_disease_details.dart';
import 'package:icare/src/features/disease_details/presentation/cubits/emergency_disease/emergency_disease_details_cubit.dart';
import 'package:icare/src/features/disease_details/presentation/cubits/medical_info_disease/medical_info_disease_details_cubit.dart';
import 'package:icare/src/features/emergency/data/datasources/emergency_local_datasource.dart';
import 'package:icare/src/features/emergency/data/datasources/emergency_remote_datasource.dart';
import 'package:icare/src/features/emergency/data/repositories/emergency_repo.dart';
import 'package:icare/src/features/emergency/domain/usecases/get_emergency_diseases.dart';
import 'package:icare/src/features/emergency/presentation/cubit/emergency_cubit.dart';
import 'package:icare/src/features/icare_bot/data/datasources/icare_bot_local_datasource.dart';
import 'package:icare/src/features/icare_bot/data/datasources/icare_bot_remote_datasource.dart';
import 'package:icare/src/features/icare_bot/data/repositories/icare_bot_repo_impl.dart';
import 'package:icare/src/features/icare_bot/domain/repositories/icare_bot_repo.dart';
import 'package:icare/src/features/icare_bot/domain/usecases/ask_icare_bot.dart';
import 'package:icare/src/features/icare_bot/domain/usecases/bookmark_icare_bot_message.dart';
import 'package:icare/src/features/icare_bot/domain/usecases/delete_bookmark.dart';
import 'package:icare/src/features/icare_bot/domain/usecases/retrieve_icare_bot_bookmarks.dart';
import 'package:icare/src/features/icare_bot/presentation/cubits/bookmark/bookmark_cubit.dart';
import 'package:icare/src/features/icare_bot/presentation/cubits/icare_bot/icare_bot_cubit.dart';
import 'package:icare/src/features/medical/data/datasources/medical_local_datasource.dart';
import 'package:icare/src/features/medical/data/datasources/medical_remote_datasource.dart';
import 'package:icare/src/features/medical/data/repositories/medical_repo.dart';
import 'package:icare/src/features/medical/domain/usecases/get_medical.dart';
import 'package:icare/src/features/medical/presentation/cubits/medical_cubit.dart';
import 'package:icare/src/features/medical_info/data/datasources/medical_info_local_datasource.dart';
import 'package:icare/src/features/medical_info/data/datasources/medical_info_remote_datasource.dart';
import 'package:icare/src/features/medical_info/data/repositories/medical_info_repo.dart';
import 'package:icare/src/features/medical_info/domain/usecases/get_medical_info.dart';
import 'package:icare/src/features/medical_info/presentation/cubit/medical_info_cubit.dart';
import 'package:icare/src/features/onboarding/data/datasources/onboarding_datasource.dart';
import 'package:icare/src/features/onboarding/data/repositories/onboarding_repo.dart';
import 'package:icare/src/features/onboarding/presentation/cubit/onboarding_cubit.dart';
import 'package:icare/src/features/speech_therapy/data/datasources/speech_therapy_remote_datasource.dart';
import 'package:icare/src/features/speech_therapy/data/repositories/speech_therapy_repo_impl.dart';
import 'package:icare/src/features/speech_therapy/domain/repositories/speech_therapy_repo.dart';
import 'package:icare/src/features/speech_therapy/domain/usecases/get_level_one_exam.dart';
import 'package:icare/src/features/speech_therapy/domain/usecases/get_level_one_training_data.dart';
import 'package:icare/src/features/speech_therapy/domain/usecases/mark_level_one.dart';
import 'package:icare/src/features/speech_therapy/presentation/cubit/speech_therapy_cubit.dart';
import 'package:icare/src/features/tiny_tales/data/datasources/tiny_tales_remote_datasource.dart';
import 'package:icare/src/features/tiny_tales/data/datasources/tiny_tales_remote_datasource_impl.dart';
import 'package:icare/src/features/tiny_tales/data/repositories/tiny_tales_repo_impl.dart';
import 'package:icare/src/features/tiny_tales/domain/repositories/tiny_tales_repo.dart';
import 'package:icare/src/features/tiny_tales/domain/usecases/bookmark_tiny_tale.dart';
import 'package:icare/src/features/tiny_tales/domain/usecases/create_tiny_tale.dart';
import 'package:icare/src/features/tiny_tales/domain/usecases/delete_tiny_tale.dart';
import 'package:icare/src/features/tiny_tales/domain/usecases/get_bookmarked_tiny_tales.dart';
import 'package:icare/src/features/tiny_tales/domain/usecases/get_tiny_tales.dart';
import 'package:icare/src/features/tiny_tales/domain/usecases/is_tiny_tale_liked_by_me.dart';
import 'package:icare/src/features/tiny_tales/domain/usecases/like_tiny_tale.dart';
import 'package:icare/src/features/tiny_tales/domain/usecases/un_bookmark_tiny_tale.dart';
import 'package:icare/src/features/tiny_tales/domain/usecases/unlike_tiny_tale.dart';
import 'package:icare/src/features/tiny_tales/domain/usecases/upload_tiny_tale_image.dart';
import 'package:icare/src/features/tiny_tales/presentation/cubits/new_tiny_tale/new_tiny_tale_cubit.dart';
import 'package:icare/src/features/tiny_tales/presentation/cubits/tiny_tales/tiny_tales_cubit.dart';
import 'package:icare/src/features/tips/data/datasources/tips_local_datasource.dart';
import 'package:icare/src/features/tips/data/datasources/tips_remote_datasource.dart';
import 'package:icare/src/features/tips/data/repositories/tips_repo.dart';
import 'package:icare/src/features/tips/domain/usecases/get_random_tip.dart';
import 'package:icare/src/features/tips/presentation/cubit/tips_cubit.dart';
import 'package:icare/src/features/user/data/datasources/user_remote_datasource.dart';
import 'package:icare/src/features/user/data/repositories/user_repo.dart';
import 'package:icare/src/features/user/domain/usecases/get_user_data.dart';
import 'package:icare/src/features/user/presentation/cubit/user_cubit.dart';

part 'src/config/locator/setup_di_for_config.dart';
part 'src/config/locator/setup_di_for_core.dart';
part 'src/config/locator/setup_di_for_cubits.dart';
part 'src/config/locator/setup_di_for_datasource.dart';
part 'src/config/locator/setup_di_for_external.dart';
part 'src/config/locator/setup_di_for_repos.dart';
part 'src/config/locator/setup_di_for_usecases.dart';

final GetIt getIt = GetIt.instance;

class DependencyInjection {
  Future<void> setup() async {
    await SetupDIForExternal.setup();

    SetupDIForConfig.setup();

    SetupDIForCore.setup();

    SetupDIForDatasource.setup();

    SetupDIForRepos.setup();

    SetupDIForUseCases.setup();

    SetupDIForCubits.setup();
  }
}
