// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGJ7RlCQmEN6TE-18UNtjhD8VmvQOcIGg',
    appId: '1:283454741737:web:bff1f99411d16992266478',
    messagingSenderId: '283454741737',
    projectId: 'icare-eeccc',
    authDomain: 'icare-eeccc.firebaseapp.com',
    storageBucket: 'icare-eeccc.appspot.com',
    measurementId: 'G-ZC68P6NREZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQWomjXb1Ah88jv3KyzN48EweLgBS-EHw',
    appId: '1:283454741737:android:90ada75199970acd266478',
    messagingSenderId: '283454741737',
    projectId: 'icare-eeccc',
    storageBucket: 'icare-eeccc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnrWrglRLD3K1q-xnOQSRmFOvjmY0_m2o',
    appId: '1:283454741737:ios:1ec3cb6483a620c0266478',
    messagingSenderId: '283454741737',
    projectId: 'icare-eeccc',
    storageBucket: 'icare-eeccc.appspot.com',
    iosBundleId: 'com.example.icare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnrWrglRLD3K1q-xnOQSRmFOvjmY0_m2o',
    appId: '1:283454741737:ios:f32c0cf1e8e4e201266478',
    messagingSenderId: '283454741737',
    projectId: 'icare-eeccc',
    storageBucket: 'icare-eeccc.appspot.com',
    iosBundleId: 'com.example.icare.RunnerTests',
  );
}
