default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_prod.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:283454741737:android:90ada75199970acd266478",
    firebase_cli_token: "1//039wMXrIPrE5lCgYIARAAGAMSNgF-L9Ir__q6uqr43BYZIILKINgAcdVBV3hJQ_2QvC3WJDhzMs_5Li1Nd1Haao3V4jQBglVk_Q",
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: ["ahmedghaly152002@gmail.com", "ahmedmuqawi@gmail.com", "mukhalifa5@gmail.com", "Osamazxzx64@gmail.com", "youmnaelghanam226@gmail.com", "byralmrshdy41@gmail.com", "hebauwk25800@gmail.com", "kareem01095134688@gmail.com", "nadanasr370@gmail.com", "weaam.ai_0482@ai.kfs.edu.eg"].join(","),
    release_notes: """
    This is a new release. Updates:
      - Finish Chat feature (Logic & UI) ✅
        * Chats are cached now
      - Update Followers, Following feature (Logic & UI) ✅
        * Followers, Following are cached now
      - Finish Change password (logic & UI) ✅
      - Handle navigation to other users profiles ✅
      - Fix Like Bug ✅
      - Finish Level one in Speech Therapy feature (logic & UI) ✅
      - Finish Score screen in Speech Therapy feature (logic & UI) ✅
  """
  )
  end
end
