default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release"
    firebase_app_distribution(
    app: ENV["FIREBASE_APP_ID"],
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
    testers: ["ahmedghaly152002@gmail.com", "ahmedmuqawi@gmail.com", "mukhalifa5@gmail.com", "Osamazxzx64@gmail.com", "youmnaelghanam226@gmail.com", "byralmrshdy41@gmail.com", "hebauwk25800@gmail.com", "kareem01095134688@gmail.com", "nadanasr370@gmail.com", "weaam.ai_0482@ai.kfs.ed"].join(","),
    release_notes: "This is a new release"
  )
  end
end
